### ISSUE TITLE
Vimeo plugin to admin issue

### ISSUE THREAD

**Issue by ianchase09** [cworreschk/grav-plugin-vimeo#2]
when i try to make a new page with the Vimeo plug in enabled, it messes with Taxonomies form and doesn't allow me to scroll down on my page creation.

![vimeo-grav-issue](https://cloud.githubusercontent.com/assets/10909818/22409867/a4cf136e-e65e-11e6-8ffc-16eceecd92da.PNG)

this is with v1.0.1

I had an error show up (didn't grab screen shot in time when i tried to fix it) that said there was a line of code between lines 50-60 (can't remember which number exactly) and then show several more errors pertaining to the admin files.

**Comment by cworreschk** [comment]
I'm sorry but I can't reproduce this error. I've tested it with Grav v1.1.14  and Admin Panel v1.2.9.
It would be great if you could keep watching. And if the error occurs again, please make a screenshot :+1:

**Comment by lbovit** [comment]
I have the same problems described above when the plugin is enabled. I am using Grav v1.1.16 - Admin v1.2.12 and I get the following javascript error:

![vimeo-js-error](https://cloud.githubusercontent.com/assets/7686933/23037774/e88b14a4-f487-11e6-9c9f-6b92a7b921a3.jpg)

**Comment by lbovit** [comment]
Seems like some issue with `GravAdmin.translations` variable that is undefined when the javascript code from the plugin is executed but when the plugin is disabled the variable `GravAdmin.translations` is populated correctly.

**Comment by cworreschk** [comment]
I think I know what exactly causes the problem. I'll fix it tomorrow. Thank you very much for your help 👍🏻

**Comment by cworreschk** [comment]
Fixed in version 1.0.2
