### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by OvalMedia** [cworreschk/grav-plugin-vimeo#9]
Installed via bin/gpm install vimeo. Vimeo icon shows up in admin editor. 
But in frontend all I get is this:
`<a href="https://vimeo.com/12345678">plugin:vimeo</a>`
Grav version ist 1.3.7 (1.3.6 didn't work either).

Any idea?

PS: I just tried the same with a fresh install of a blog skeleton. Same result :(

**Comment by OvalMedia** [comment]
Forget it. I was fed a wrong video url (private link).

**Comment by cworreschk** [comment]
Okay :+1:
